# Generated by Django 2.0.5 on 2018-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_art', models.CharField(max_length=150)),
                ('contenu_art', models.TextField(max_length=500)),
                ('last_accessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=150)),
                ('contenu_english', models.TextField(max_length=500)),
                ('last_accessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Infographie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_info', models.CharField(max_length=150)),
                ('contenu_info', models.TextField(max_length=500)),
                ('last_accessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_office', models.CharField(max_length=150)),
                ('contenu_office', models.TextField(max_length=500)),
                ('last_accessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Programmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_Programmation', models.CharField(max_length=150)),
                ('contenu_Programmation', models.TextField(max_length=500)),
                ('last_accessed', models.DateTimeField()),
            ],
        ),
    ]
